### ISSUE TITLE
在Google Play审核，提示此安全问题

### ISSUE THREAD

**Issue by superoidlau** [wangchenyan/android-common#2]
![image](https://github.com/user-attachments/assets/6d4d2717-7686-423a-8d43-64e3200f113f)

Hi chenyan:

我正在使用的您的库【android-common】，其中有一个安全问题，见上图。

Your app is using an unsafe implementation of WebViewClient.onReceivedSslError handler. Please see this Google Help Center article for details, including the deadline for fixing the vulnerability.

sv:deadline:01/28/2025
top.wangchenyan.common.ext.WebClient

官方文档：
https://support.google.com/faqs/answer/7071387

**Comment by wangchenyan** [comment]
你好，代码已删除，请使用 1.0.2-beta03 版本
